import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export interface Receipt {
  id: string;
  receipt_number: string;
  student_id: string | null;
  student_name: string;
  description: string;
  amount: number;
  date: string;
  created_at: string;
}

export interface ReceiptFormData {
  student_id?: string;
  student_name: string;
  description: string;
  amount: number;
  date: string;
}

export function useReceipts() {
  return useQuery({
    queryKey: ["receipts"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("receipts")
        .select("*")
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data as Receipt[];
    },
  });
}

export function useCreateReceipt() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (formData: ReceiptFormData) => {
      // Receipt number is now auto-generated by database default
      // This uses a PostgreSQL sequence for atomic, race-condition-free generation
      const { data, error } = await supabase
        .from("receipts")
        .insert([formData])
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["receipts"] });
      toast.success("Recibo gerado com sucesso!");
    },
    onError: (error) => {
      toast.error("Erro ao gerar recibo: " + error.message);
    },
  });
}
